name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  # Checks that commits follow the conventional commit guide and blocks fixup/squash commits.
  commit-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Block merging fixup commits
        uses: 13rac1/block-fixup-merge-action@v2.0.0

      - name: Enforce Conventional Commits
        uses: wagoid/commitlint-github-action@v4

  # Check that the rust and js files are formatted correctly
  format-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cargo fmt check
        run: cargo fmt -- --check

      - name: Node fmt check
        run: |
          npm install
          npm run check:fmt:prettier

  # Main job: builds the crate and runs the tests
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cargo
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install node deps
      run: |
       npm install
       npm run build:node_tests
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
