name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:

  # Check that the rust and js files are formatted correctly
  format-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Setup Rust nightly (formatting)
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: nightly

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check toml files sorting
        run: |
          cargo install cargo-sort
          cargo sort --check

      - name: Cargo fmt check
        run: cargo +nightly fmt -- --check

      - name: Node fmt check
        run: |
          npm install
          npm run check:fmt:prettier

  # Main job: builds the crate and runs the tests
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup cargo
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run clippy
      run: cargo clippy --verbose -- -D warnings

    - name: Install node deps
      run: |
       npm install
       npm run build:node_tests
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo t --verbose
